### ISSUE TITLE
Need a detection of compiler's support for C++17 with fallback to C++14

### ISSUE THREAD

**Issue by Wohlstand** [jpcima/ring-buffer#2]
Also, at me system GCC-5.4 doesn't supports C++17, but supports C++14. Configure fails when C++17 is set, however, works perfect when C++14 is set in CMakeLists.txt. Why not to detect C++17 support or even just rely on GCC version to specify C++ standard available since specific version.

**Comment by jpcima** [comment]
I see. I will just let cmake pick the latest version it knows.
And I'll insert a feature check just behind that.

**Comment by jpcima** [comment]
Please check if the latest does the correct thing on cmake 3.5.

**Comment by jpcima** [comment]
Note: You keep C++ versions back in your projects, because of Watcom and old environments.
This project could be made retrocompatible even more, but it would be much less elegant.
Basically you replace C++14 mutex stuff with Boost, and std::atomic with either Boost, or volatile.

**Comment by Wohlstand** [comment]
Anyway, I only want to build this and ADLJack without of re-applying of workarounds after each pull. The Watcom is still not supported right and some stack processing bugs are found while I experimented with it. I have tried Watcom to target libADLMIDI for DOS with HW-OPL3 chip support with one of well-known compilers together with already supporting DJGPP which working well. Inside of libADLMIDI/libOPNMIDI I keeping C++98 standard supported to have it well-compiled on most of widely using compilers include some oldies.

**Comment by Wohlstand** [comment]
> Please check if the latest does the correct thing on cmake 3.5.

It doesn't works because of `compiler does not support at least C++14` message, as in my case the full list of compiler features list is:
```
cxx_aggregate_default_initializers
cxx_alias_templates
cxx_alignas
cxx_alignof
cxx_attribute_deprecated
cxx_attributes
cxx_auto_type
cxx_binary_literals
cxx_constexpr
cxx_contextual_conversions
cxx_decltype
cxx_decltype_auto
cxx_decltype_incomplete_return_types
cxx_defaulted_functions
cxx_defaulted_move_initializers
cxx_default_function_template_args
cxx_delegating_constructors
cxx_deleted_functions
cxx_digit_separators
cxx_enum_forward_declarations
cxx_explicit_conversions
cxx_extended_friend_declarations
cxx_extern_templates
cxx_final
cxx_func_identifier
cxx_generalized_initializers
cxx_generic_lambdas
cxx_inheriting_constructors
cxx_inline_namespaces
cxx_lambda_init_captures
cxx_lambdas
cxx_local_type_template_args
cxx_long_long_type
cxx_noexcept
cxx_nonstatic_member_init
cxx_nullptr
cxx_override
cxx_range_for
cxx_raw_string_literals
cxx_reference_qualified_functions
cxx_relaxed_constexpr
cxx_return_type_deduction
cxx_right_angle_brackets
cxx_rvalue_references
cxx_sizeof_member
cxx_static_assert
cxx_strong_enums
cxx_template_template_parameters
cxx_thread_local
cxx_trailing_return_types
cxx_unicode_literals
cxx_uniform_initialization
cxx_unrestricted_unions
cxx_user_literals
cxx_variable_templates
cxx_variadic_macros
cxx_variadic_templates
```

**Comment by jpcima** [comment]
Jesus OK it doesn't know features. Let's improvise something else.

**Comment by jpcima** [comment]
New method. Please try.

**Comment by Wohlstand** [comment]
It gives both CXX Compiler flags `1`, but errors with:
```
-- Building for C++ standard 17
Flags: 1 1
-- Configuring done
CMake Error at thirdparty/ring-buffer/CMakeLists.txt:36 (add_executable):
  CXX_STANDARD is set to invalid value '17'


CMake Error at thirdparty/ring-buffer/CMakeLists.txt:32 (add_library):
  CXX_STANDARD is set to invalid value '17'
```

I had to put this line:
```
message("Flags: ${HAVE_CXXFLAG_STDCXX17} ${HAVE_CXXFLAG_STDCXX14}")
```

**Comment by jpcima** [comment]
OK you know what, to hell with this. Let's do simple.
The user passes -DRING_BUFFER_CXX_STANDARD=14. It sets the C++ standard.
RING_BUFFER_CXX_STANDARD not set => autodetect

PS: make sure to clear cmake cache between tests

EDIT: I updated. You can try.

**Comment by Wohlstand** [comment]
Good, now it works! :fox_face: 
Also, you would make that `RING_BUFFER_CXX_STANDARD` variable be cachable with adding of description.

**Comment by jpcima** [comment]
You're right. Done.
